version: '3'
services:
  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    ports:
      - '5002:5002'
  shipping-service:
    build:
      context: ./shipping-service
      dockerfile: Dockerfile
    ports:
      - '5003:5003'
  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    ports:
      - '5008:5008'
